packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  lefthook: true
  workerd: true

catalog:
  typescript: 7.0.2
  "@cloudflare/vitest-pool-workers": 0.20.1
  "@tsndr/cloudflare-worker-jwt": 3.2.1
  "@biomejs/biome": 2.5.6
  hono: 4.12.33
  wrangler: 4.117.0
  drizzle-orm: 0.45.2
  drizzle-kit: 0.31.10
  "@tidbcloud/serverless": 0.3.0
  uuidv7: 1.2.1
  vitest: 4.1.10
  dotenv: ^17.4.2
  mysql2: 3.23.2
  valibot: 1.4.2
  "@hono/valibot-validator": 0.6.1
  "@types/node": 24.13.3

minimumReleaseAgeExclude:
  - hono@4.12.34
