/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as UnauthenticatedAuthRouteImport } from './routes/_unauthenticated/auth'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding/index'
import { Route as AuthenticatedOnboardingCompleteRouteImport } from './routes/_authenticated/onboarding/complete'
import { Route as AuthenticatedOnboardingShopRouteImport } from './routes/_authenticated/onboarding/shop'
import { Route as AuthenticatedOnboardingWelcomeRouteImport } from './routes/_authenticated/onboarding/welcome'
import { Route as UnauthenticatedAuthErrorRouteImport } from './routes/_unauthenticated/auth/error'
import { Route as UnauthenticatedAuthForgotPasswordRouteImport } from './routes/_unauthenticated/auth/forgot-password'
import { Route as UnauthenticatedAuthLoginRouteImport } from './routes/_unauthenticated/auth/login'
import { Route as UnauthenticatedAuthRegisterRouteImport } from './routes/_unauthenticated/auth/register'
import { Route as UnauthenticatedAuthResetPasswordRouteImport } from './routes/_unauthenticated/auth/reset-password'
import { Route as UnauthenticatedAuthSuccessRouteImport } from './routes/_unauthenticated/auth/success'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedAuthRoute = UnauthenticatedAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingCompleteRoute =
  AuthenticatedOnboardingCompleteRouteImport.update({
    id: '/onboarding/complete',
    path: '/onboarding/complete',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingShopRoute =
  AuthenticatedOnboardingShopRouteImport.update({
    id: '/onboarding/shop',
    path: '/onboarding/shop',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingWelcomeRoute =
  AuthenticatedOnboardingWelcomeRouteImport.update({
    id: '/onboarding/welcome',
    path: '/onboarding/welcome',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const UnauthenticatedAuthErrorRoute =
  UnauthenticatedAuthErrorRouteImport.update({
    id: '/error',
    path: '/error',
    getParentRoute: () => UnauthenticatedAuthRoute,
  } as any)
const UnauthenticatedAuthForgotPasswordRoute =
  UnauthenticatedAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => UnauthenticatedAuthRoute,
  } as any)
const UnauthenticatedAuthLoginRoute =
  UnauthenticatedAuthLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => UnauthenticatedAuthRoute,
  } as any)
const UnauthenticatedAuthRegisterRoute =
  UnauthenticatedAuthRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => UnauthenticatedAuthRoute,
  } as any)
const UnauthenticatedAuthResetPasswordRoute =
  UnauthenticatedAuthResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => UnauthenticatedAuthRoute,
  } as any)
const UnauthenticatedAuthSuccessRoute =
  UnauthenticatedAuthSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => UnauthenticatedAuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof UnauthenticatedAuthRouteWithChildren
  '/onboarding/complete': typeof AuthenticatedOnboardingCompleteRoute
  '/onboarding/shop': typeof AuthenticatedOnboardingShopRoute
  '/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/auth/error': typeof UnauthenticatedAuthErrorRoute
  '/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/register': typeof UnauthenticatedAuthRegisterRoute
  '/auth/reset-password': typeof UnauthenticatedAuthResetPasswordRoute
  '/auth/success': typeof UnauthenticatedAuthSuccessRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof UnauthenticatedAuthRouteWithChildren
  '/onboarding/complete': typeof AuthenticatedOnboardingCompleteRoute
  '/onboarding/shop': typeof AuthenticatedOnboardingShopRoute
  '/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/auth/error': typeof UnauthenticatedAuthErrorRoute
  '/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/register': typeof UnauthenticatedAuthRegisterRoute
  '/auth/reset-password': typeof UnauthenticatedAuthResetPasswordRoute
  '/auth/success': typeof UnauthenticatedAuthSuccessRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_unauthenticated/auth': typeof UnauthenticatedAuthRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/onboarding/complete': typeof AuthenticatedOnboardingCompleteRoute
  '/_authenticated/onboarding/shop': typeof AuthenticatedOnboardingShopRoute
  '/_authenticated/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/_unauthenticated/auth/error': typeof UnauthenticatedAuthErrorRoute
  '/_unauthenticated/auth/forgot-password': typeof UnauthenticatedAuthForgotPasswordRoute
  '/_unauthenticated/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/_unauthenticated/auth/register': typeof UnauthenticatedAuthRegisterRoute
  '/_unauthenticated/auth/reset-password': typeof UnauthenticatedAuthResetPasswordRoute
  '/_unauthenticated/auth/success': typeof UnauthenticatedAuthSuccessRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding/complete'
    | '/onboarding/shop'
    | '/onboarding/welcome'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/success'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding/complete'
    | '/onboarding/shop'
    | '/onboarding/welcome'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/success'
    | '/onboarding'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_unauthenticated/auth'
    | '/_authenticated/'
    | '/_authenticated/onboarding/complete'
    | '/_authenticated/onboarding/shop'
    | '/_authenticated/onboarding/welcome'
    | '/_unauthenticated/auth/error'
    | '/_unauthenticated/auth/forgot-password'
    | '/_unauthenticated/auth/login'
    | '/_unauthenticated/auth/register'
    | '/_unauthenticated/auth/reset-password'
    | '/_unauthenticated/auth/success'
    | '/_authenticated/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/auth': {
      id: '/_unauthenticated/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof UnauthenticatedAuthRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/complete': {
      id: '/_authenticated/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof AuthenticatedOnboardingCompleteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/shop': {
      id: '/_authenticated/onboarding/shop'
      path: '/onboarding/shop'
      fullPath: '/onboarding/shop'
      preLoaderRoute: typeof AuthenticatedOnboardingShopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/welcome': {
      id: '/_authenticated/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof AuthenticatedOnboardingWelcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/auth/error': {
      id: '/_unauthenticated/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof UnauthenticatedAuthErrorRouteImport
      parentRoute: typeof UnauthenticatedAuthRoute
    }
    '/_unauthenticated/auth/forgot-password': {
      id: '/_unauthenticated/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof UnauthenticatedAuthForgotPasswordRouteImport
      parentRoute: typeof UnauthenticatedAuthRoute
    }
    '/_unauthenticated/auth/login': {
      id: '/_unauthenticated/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof UnauthenticatedAuthLoginRouteImport
      parentRoute: typeof UnauthenticatedAuthRoute
    }
    '/_unauthenticated/auth/register': {
      id: '/_unauthenticated/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof UnauthenticatedAuthRegisterRouteImport
      parentRoute: typeof UnauthenticatedAuthRoute
    }
    '/_unauthenticated/auth/reset-password': {
      id: '/_unauthenticated/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof UnauthenticatedAuthResetPasswordRouteImport
      parentRoute: typeof UnauthenticatedAuthRoute
    }
    '/_unauthenticated/auth/success': {
      id: '/_unauthenticated/auth/success'
      path: '/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof UnauthenticatedAuthSuccessRouteImport
      parentRoute: typeof UnauthenticatedAuthRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOnboardingCompleteRoute: typeof AuthenticatedOnboardingCompleteRoute
  AuthenticatedOnboardingShopRoute: typeof AuthenticatedOnboardingShopRoute
  AuthenticatedOnboardingWelcomeRoute: typeof AuthenticatedOnboardingWelcomeRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOnboardingCompleteRoute: AuthenticatedOnboardingCompleteRoute,
  AuthenticatedOnboardingShopRoute: AuthenticatedOnboardingShopRoute,
  AuthenticatedOnboardingWelcomeRoute: AuthenticatedOnboardingWelcomeRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedAuthRouteChildren {
  UnauthenticatedAuthErrorRoute: typeof UnauthenticatedAuthErrorRoute
  UnauthenticatedAuthForgotPasswordRoute: typeof UnauthenticatedAuthForgotPasswordRoute
  UnauthenticatedAuthLoginRoute: typeof UnauthenticatedAuthLoginRoute
  UnauthenticatedAuthRegisterRoute: typeof UnauthenticatedAuthRegisterRoute
  UnauthenticatedAuthResetPasswordRoute: typeof UnauthenticatedAuthResetPasswordRoute
  UnauthenticatedAuthSuccessRoute: typeof UnauthenticatedAuthSuccessRoute
}

const UnauthenticatedAuthRouteChildren: UnauthenticatedAuthRouteChildren = {
  UnauthenticatedAuthErrorRoute: UnauthenticatedAuthErrorRoute,
  UnauthenticatedAuthForgotPasswordRoute:
    UnauthenticatedAuthForgotPasswordRoute,
  UnauthenticatedAuthLoginRoute: UnauthenticatedAuthLoginRoute,
  UnauthenticatedAuthRegisterRoute: UnauthenticatedAuthRegisterRoute,
  UnauthenticatedAuthResetPasswordRoute: UnauthenticatedAuthResetPasswordRoute,
  UnauthenticatedAuthSuccessRoute: UnauthenticatedAuthSuccessRoute,
}

const UnauthenticatedAuthRouteWithChildren =
  UnauthenticatedAuthRoute._addFileChildren(UnauthenticatedAuthRouteChildren)

interface UnauthenticatedRouteChildren {
  UnauthenticatedAuthRoute: typeof UnauthenticatedAuthRouteWithChildren
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedAuthRoute: UnauthenticatedAuthRouteWithChildren,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
